spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.137.10:3306/pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
mybatis-plus:
  # 默认值
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    banner: off
    db-config:
      id-type: auto
server:
  port: 10000
  undertow:
    io-threads: 2
    worker-threads: 16

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  # 请求处理的超时时间
  ReadTimeout: 40000
  # 请求连接的超时时间
  ConnectTimeout: 10000
  # 对当前实例的重试次数
  maxAutoRetries: 1
  # 切换实例的重试次数
  maxAutoRetriesNextServer: 3
  # 重试默认都是只支持get请求，如果设置位true则会多所有请求开启重试，但不建议这样设置，因为post请求大多都是写入请求，如果要支持重试，服务自身的幂等性一定要健壮
  okToRetryOnAllOperations: false
  #ribbon缓存刷新时间
  ServerListRefreshInterval: 3000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: C:\Users\Simple\Documents\CATALINA.BASE\619\${spring.application.name}.txt
  level:
    io:
      github:
        thesixonenine:
          product:
            controller: debug
            service:
              impl: debug
            dao: debug
    com:
      alibaba:
        nacos:
          client:
            config:
              impl: warn