spring:
  cloud:
    gateway:
      routes:
      # 后台的商品接口相关路由
      - id: admin_product_route
        uri: lb://product
        predicates:
        - Path=/renren-fast/product/**
        filters:
        - RewritePath=/renren-fast(?<segment>/?.*), $\{segment}

      # 后台的会员接口相关路由
      - id: admin_member_route
        uri: lb://member
        predicates:
          - Path=/renren-fast/member/**
        filters:
          - RewritePath=/renren-fast(?<segment>/?.*), $\{segment}
      # 后台的库存接口相关路由
      - id: admin_ware_route
        uri: lb://ware
        predicates:
          - Path=/renren-fast/ware/**
        filters:
          - RewritePath=/renren-fast(?<segment>/?.*), $\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        # /red/1 or /red/blue or /blue/green
        # - Path=/red/{segment},/blue/{segment}
        - Path=/renren-fast/**
        # filters:
        # - RewritePath=/renren-fast(?<segment>/?.*), $\{segment}


      # 用户侧相关路由
      - id: jdmall_index_route
        uri: lb://product
        predicates:
          - Host=jdmall.com, item.jdmall.com
      - id: jdmall_search_route
        uri: lb://search
        predicates:
          - Host=search.jdmall.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: C:\Users\Simple\Documents\CATALINA.BASE\619\${spring.application.name}.txt
  level:
    com:
      alibaba:
        nacos:
          client:
            config:
              impl: warn