management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: C:\Users\Simple\Documents\CATALINA.BASE\619\${spring.application.name}.txt