server:
  port: 13000
  undertow:
    io-threads: 2
    worker-threads: 16
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.137.10
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: C:\Users\Simple\Documents\CATALINA.BASE\619\${spring.application.name}.txt
  level:
    com:
      alibaba:
        nacos:
          client:
            config:
              impl: warn

thread:
  core-pool-size: 20
  maximum-pool-size: 50
  keep-alive-time: 10